name: Generate Snake Game from GitHub Contribution Grid

on:
  schedule: # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run the workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Generate the snake game from GitHub contribution grid
      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ahmeddavids
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 3: Push the content to the output branch
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
